# Generated by Django 5.1.4 on 2025-01-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Upload Image of the book')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Enter a title of the book')),
                ('description', models.TextField(verbose_name='Enter a description of the book')),
                ('price', models.FloatField(verbose_name='Enter the price of the book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('fantasy', 'fantasy'), ('comedy', 'comedy'), ('romance', 'romance')], default='fantasy', max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=100, verbose_name="Enter the autor's email address")),
                ('author', models.CharField(max_length=100, verbose_name="Enter the author's name")),
                ('trailer', models.URLField(verbose_name='Enter the trailer URL')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Enter a review of the book')),
                ('rate', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐', max_length=100, verbose_name='your rating of the book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='library_blog.booksmodel')),
            ],
        ),
    ]
