# Generated by Django 5.1.4 on 2025-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Books',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(to='book_tags.tag'),
        ),
    ]
