# Generated by Django 5.1.3 on 2025-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tags', '0002_rename_product_books_tag_name_alter_books_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
