# Generated by Django 5.1.3 on 2024-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Upload Image of the book')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Enter a title of the book')),
                ('description', models.TextField(verbose_name='Enter a description of the book')),
                ('price', models.FloatField(verbose_name='Enter the price of the book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('fantasy', 'fantasy'), ('comedy', 'comedy'), ('romance', 'romance')], default='fantasy', max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=100, verbose_name="Enter the autor's email address")),
                ('author', models.CharField(max_length=100, verbose_name="Enter the author's name")),
                ('trailer', models.URLField(verbose_name='Enter the trailer URL')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
